version: '2'
services:
    flashcards-app:
        image: flashcards
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://flashcards-mysql:3306/flashcards?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    flashcards-mysql:
        extends:
            file: mysql.yml
            service: flashcards-mysql
